caddy:
  container_name: caddy
  image: zzrot/alpine-caddy
  ports:
    - 80:80
  links:
    - standpoint_server
  volumes:
    - "./caddy/Caddyfile:/etc/Caddyfile"
topic_api:
  container_name: topic_api
  build: ./topic_api
  environment:
    PORT: 4567
  ports:
    - "4567:4567"
  volumes:
    - "./topic_api:/app"

point_extractor:
  container_name: point_extractor
  build: ./point_extractor
  links:
    - corenlp_server
  ports:
    - "3456:3456"
  volumes:
    - "./point_extractor:/app"

corenlp_server:
  container_name: corenlp_server
  build: ./corenlp_server
  ports:
    - "9000:9000"
  environment:
    RELEASE: "stanford-corenlp-full-2015-12-09"
    RELEASE_URL: "http://nlp.stanford.edu/software/stanford-corenlp-full-2015-12-09.zip"

standpoint_server:
  container_name: standpoint_server
  build: ./standpoint_server
  ports:
   - "3000:3000"
  links:
    - standpoint_server_postgres:postgres
    - standpoint_worker
  volumes:
    - "./standpoint_server:/app"
  environment:
    RAILS_ENV: "production"
    SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
    POSTGRES_USER: "${POSTGRES_USER}"
    POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

standpoint_worker:
  container_name: standpoint_worker
  build: ./standpoint_server
  command: bundle exec rake jobs:work
  links:
    - standpoint_server_postgres:postgres
    - point_extractor
  volumes:
    - "./standpoint_server:/app"
  environment:
    RAILS_ENV: "production"
    SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
    POSTGRES_USER: "${POSTGRES_USER}"
    POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

standpoint_server_postgres:
  container_name: standpoint_server_postgres
  image: postgres:9.4.5
  ports:
    - "5432:5432"
  volumes:
    - standpoint_postgres_volume:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: "${POSTGRES_USER}"
    POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
